package com.helpinminutes.api.batches.model;

public enum BookingBatchStatus {
  CREATED,
  PARTIAL,
  COMPLETED,
  CANCELLED,
  PENDING_AUDIT,
  ON_HOLD,
  PENDING_MEDIATOR,
  MEDIATOR_ACCEPTED,
  MEDIATOR_DISPATCHING,
  MEDIATOR_IN_PROGRESS,
  MEDIATOR_STARTED,
  MEDIATOR_COMPLETED
}
