ALTER TABLE tasks
  ALTER COLUMN skill_id DROP NOT NULL;

ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS title VARCHAR(140),
  ADD COLUMN IF NOT EXISTS urgency VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN IF NOT EXISTS time_minutes INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS budget_paise BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arrival_selfie_url TEXT,
  ADD COLUMN IF NOT EXISTS arrival_selfie_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS arrival_selfie_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS arrival_selfie_address TEXT,
  ADD COLUMN IF NOT EXISTS arrival_selfie_captured_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completion_selfie_url TEXT,
  ADD COLUMN IF NOT EXISTS completion_selfie_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS completion_selfie_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS completion_selfie_address TEXT,
  ADD COLUMN IF NOT EXISTS completion_selfie_captured_at TIMESTAMPTZ;

