server {
    listen 80;
    listen [::]:80;
    server_name livekit.mysuperhero.xyz turn.mysuperhero.xyz;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 404;
    }
}
